---
title: "12 Adjusted TPR"
subtitle: "aTPR - PNAS manuscript (initial submission) - Table 1"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, include= FALSE}
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(patchwork)
library(ggh4x)

#folder = '/Users/Sarah/Box/Research/Dissertation/12 Adjusted TPR/numerical/12.05.01/rwdout/'
folder = 'Z:/D12-aTPR/12.05.01/rwdout/'
simlab = 'rwd03-palliative-connect-replicate-original-'
```

# Make Supplemental Table - Gender
```{r supfig.gender}
# Read in bootstrapped estimates
load(paste0(folder,simlab,'gender.Rdata'))

# Merge in naive estimates to each row and compute differences
diffs.gender <- gender.boot.comp %>%
                    mutate(estimate= 'adjusted'
                           , method = paste0(calmethod,"+",densitymethod)) %>%
                    bind_rows(gender.boot.comp %>%
                                  select(GENDER_CODE, idset, tau, TPR) %>%
                                  unique() %>%
                                  mutate(estimate = 'naive'
                                         , method = 'none')
                    ) %>%
                left_join(gender.boot.comp  %>%
                            filter(GENDER_CODE == 'M') %>%
                            select(idset, tau, TPR) %>%
                            unique() %>%
                            rename(TPR.ref = TPR)
                          ) %>%
                mutate(delta = if_else(estimate == 'naive', TPR-TPR.ref, aTPR-TPR.ref)
                       ,group ='Gender') %>%
                rename(s = GENDER_CODE)

# Get mean and CIs for delta
diffs.gender.sum <- diffs.gender %>%
                      group_by(group, s, tau, estimate, method, calmethod, densitymethod) %>%
                      summarize(n = n()
                                ,TPR.boot.mean = mean(TPR)
                                ,TPR.boot.lower = quantile(TPR,0.025, na.rm=TRUE)
                                ,TPR.boot.upper = quantile(TPR,0.975, na.rm=TRUE)
                                ,aTPR.boot.mean = mean(aTPR)
                                ,aTPR.boot.lower = quantile(aTPR,0.025, na.rm=TRUE)
                                ,aTPR.boot.upper = quantile(aTPR,0.975, na.rm=TRUE)
                                ,delta.boot.mean = mean(delta)
                                ,delta.boot.lower =quantile(delta,0.025, na.rm=TRUE)
                                ,delta.boot.upper = quantile(delta, 0.975, na.rm=TRUE)
                                )
```

# Make Supplemental Table - Race
```{r supfig.race}
# Read in bootstrapped estimates
load(paste0(folder,simlab,'race.Rdata'))

# Merge in naive estimates to each row and compute differences
diffs.race <- race.boot.comp %>%
                    mutate(estimate= 'adjusted'
                           , method = paste0(calmethod,"+",densitymethod)) %>%
                    bind_rows(race.boot.comp %>%
                                  select(race_ethnicity, idset, tau, TPR) %>%
                                  unique() %>%
                                  mutate(estimate = 'naive'
                                         , method = 'none')
                    ) %>%
                left_join(race.boot.comp  %>%
                            filter(race_ethnicity == 'Non_hispanic_white') %>%
                            select(idset, tau, TPR) %>%
                            unique() %>%
                            rename(TPR.ref = TPR)
                          ) %>%
                mutate(delta = if_else(estimate == 'naive', TPR-TPR.ref, aTPR-TPR.ref)
                       ,group = 'Race') %>%
                rename(s = race_ethnicity)
    

# Get mean and CIs for delta
diffs.race.sum <- diffs.race %>%
                      group_by(group, s, tau, estimate, method, calmethod, densitymethod) %>%
                      summarize(n = n()
                                ,TPR.boot.mean = mean(TPR)
                                ,TPR.boot.lower = quantile(TPR,0.025, na.rm=TRUE)
                                ,TPR.boot.upper = quantile(TPR,0.975, na.rm=TRUE)
                                ,aTPR.boot.mean = mean(aTPR)
                                ,aTPR.boot.lower = quantile(aTPR,0.025, na.rm=TRUE)
                                ,aTPR.boot.upper = quantile(aTPR,0.975, na.rm=TRUE)
                                ,delta.boot.mean = mean(delta)
                                ,delta.boot.lower =quantile(delta,0.025, na.rm=TRUE)
                                ,delta.boot.upper = quantile(delta, 0.975, na.rm=TRUE)
                                )
```

# Make Supplemental Figure - Gender x Race
```{r supfig.genderrace}
# Read in bootstrapped estimates
load(paste0(folder,simlab,'genderrace.Rdata'))

# Merge in naive estimates to each row and compute differences
diffs.genderrace <- genderrace.boot.comp %>%
                    mutate(estimate= 'adjusted'
                           , method = paste0(calmethod,"+",densitymethod)) %>%
                    bind_rows(genderrace.boot.comp %>%
                                  select(GENDERxRACE, idset, tau, TPR) %>%
                                  unique() %>%
                                  mutate(estimate = 'naive'
                                         , method = 'none')
                    ) %>%
                left_join(genderrace.boot.comp  %>%
                            filter(GENDERxRACE == 'M-Non_hispanic_white') %>%
                            select(idset, tau, TPR) %>%
                            unique() %>%
                            rename(TPR.ref = TPR)
                          ) %>%
                mutate(delta = if_else(estimate == 'naive', TPR-TPR.ref, aTPR-TPR.ref)
                       ,group = 'GenderxRace') %>%
                rename(s = GENDERxRACE)

# Get mean and CIs for delta
diffs.genderrace.sum <- diffs.genderrace %>%
                      group_by(group, s, tau, estimate, method, calmethod, densitymethod) %>%
                      summarize(n = n()
                                ,TPR.boot.mean = mean(TPR, na.rm = TRUE)
                                ,TPR.boot.lower = quantile(TPR,0.025, na.rm=TRUE)
                                ,TPR.boot.upper = quantile(TPR,0.975, na.rm=TRUE)
                                ,aTPR.boot.mean = mean(aTPR, na.rm = TRUE)
                                ,aTPR.boot.lower = quantile(aTPR,0.025, na.rm=TRUE)
                                ,aTPR.boot.upper = quantile(aTPR,0.975, na.rm=TRUE)
                                ,delta.boot.mean = mean(delta, na.rm = TRUE)
                                ,delta.boot.lower =quantile(delta,0.025, na.rm=TRUE)
                                ,delta.boot.upper = quantile(delta, 0.975, na.rm=TRUE)
                                )
```

```{r}
options(digits=4)
# naive
diffs.gender.sum %>%
    bind_rows(diffs.race.sum) %>%
    bind_rows(diffs.genderrace.sum) %>%
    ungroup() %>%
    filter(abs(tau-0.3) <0.001 , method == 'none') %>%
    select(group, s, n
           , TPR.boot.mean, TPR.boot.lower, TPR.boot.upper)

diffs.gender.sum %>%
    bind_rows(diffs.race.sum) %>%
    bind_rows(diffs.genderrace.sum) %>%
    ungroup() %>%
    filter(abs(tau-0.3) <0.001 , method == 'none') %>%
    select(group, s, n
           , delta.boot.mean, delta.boot.lower, delta.boot.upper)

# adjusted - Q+Q 
diffs.gender.sum %>%
    mutate(group = 'Gender') %>%
    bind_rows(diffs.race.sum %>%
                mutate(group = 'Race')) %>%
    bind_rows(diffs.genderrace.sum %>%
                  mutate(group= 'GenderxRace')) %>%
    ungroup() %>%
    filter(abs(tau-0.3) <0.001 , method == 'qlogit+qlogit') %>%
    select(group, s, n, tau
           , aTPR.boot.mean, aTPR.boot.lower, aTPR.boot.upper)
diffs.gender.sum %>%
    mutate(group = 'Gender') %>%
    bind_rows(diffs.race.sum %>%
                mutate(group = 'Race')) %>%
    bind_rows(diffs.genderrace.sum %>%
                  mutate(group= 'GenderxRace')) %>%
    ungroup() %>%
    filter(abs(tau-0.3) <0.001 , method == 'qlogit+qlogit') %>%
    select(group, s, n
             , delta.boot.mean, delta.boot.lower, delta.boot.upper)
```

```{r}
load(paste0(folder,"pallconnect.Rdata"))

freq.gender <- pallconnect %>%
                group_by(GENDER_CODE) %>%
                summarise(n = n()
                          ,ndeaths = sum(X6_month_mortality)
                          ,mortrate = mean(X6_month_mortality)
                          ,meanrisk = mean(preds_orig)
                          ,highrisk30 = mean(preds_orig > 0.30)) %>%
                ungroup() %>%
                mutate(group = 'Gender') %>%
                rename(s = GENDER_CODE)
freq.gender 

freq.race <- pallconnect %>%
                group_by(race_ethnicity) %>%
                summarise(n = n()
                          ,ndeaths = sum(X6_month_mortality)
                          ,mortrate = mean(X6_month_mortality)
                          ,meanrisk = mean(preds_orig)
                          ,highrisk30 = mean(preds_orig > 0.30)) %>%
                ungroup() %>%
                mutate(group = 'Race') %>%
                rename(s = race_ethnicity)
freq.race

freq.genderrace <- pallconnect %>%
                group_by(GENDER_CODE, race_ethnicity) %>%
                summarise(n = n()
                          ,ndeaths = sum(X6_month_mortality)
                          ,mortrate = mean(X6_month_mortality)
                          ,meanrisk = mean(preds_orig)
                          ,highrisk30 = mean(preds_orig > 0.30)) %>%
                ungroup() %>%
                mutate(group = 'Gender x Race'
                       ,s = paste0(GENDER_CODE,"-",race_ethnicity))
freq.genderrace

```