---
title: "12 Adjusted TPR"
subtitle: "aTPR - PNAS manuscript (initial submission) Figure 2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, include= FALSE}
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(patchwork)
library(ggh4x)

#folder = '/Users/Sarah/Box/Research/Dissertation/12 Adjusted TPR/numerical/12.05.01/simout/'
folder = '/Users/hegarty/Library/CloudStorage/Box-Box/Research/Dissertation/12 Adjusted TPR/numerical/12.05.01/simout/'
bf = '/Users/hegarty/Library/CloudStorage/Box-Box/Research/Dissertation/12 Adjusted TPR/numerical/12.05.01/r1out/'
n = '1k' 
simlab = paste0('sim01-aTPR-alpha24-',n)


cloglog <- function(z){
  log(-log(1-z))
}
```


# Read in simulation output data
```{r}
# Load Results from fairRisk package
diffs <- NULL
bench1Mgam <- NULL
for(k in c(1,5,16,20)){
  load(paste0(folder,simlab,'_setting_',k,'_with_benchmarks.Rdata'))
  
  settings <- out$settings
  diffs <- diffs %>%
                  bind_rows(out[["df_diffs (refgp = 1)"]] %>%
                              mutate(setting_id = k
                                     ,n1 = settings$n[1]
                                     ,n2 = settings$n[2]
                                     ,alpha1 = settings$alpha[1]
                                     ,alpha2 = settings$alpha[2]
                                     ,beta1 = settings$beta[1]
                                     ,beta2 = settings$beta[2]
                                     ,theta.a1 = settings$theta.a[1]
                                     ,theta.a2 = settings$theta.a[2]
                                     ,theta.b1 = settings$theta.b[1]
                                     ,theta.b2 = settings$theta.b[2]
                                     ,sigeps1 = settings$sigeps[1]
                                     ,sigeps2 = settings$sigeps[2]
                                     ,h1 = settings$h[1]
                                     ,h2 = settings$h[2]
                                     ,ref = 1)) %>%
                    bind_rows(out[["df_diffs (refgp = 2)"]] %>%
                              mutate(setting_id = k
                                     ,n1 = settings$n[1]
                                     ,n2 = settings$n[2]
                                     ,alpha1 = settings$alpha[1]
                                     ,alpha2 = settings$alpha[2]
                                     ,beta1 = settings$beta[1]
                                     ,beta2 = settings$beta[2]
                                     ,theta.a1 = settings$theta.a[1]
                                     ,theta.a2 = settings$theta.a[2]
                                     ,theta.b1 = settings$theta.b[1]
                                     ,theta.b2 = settings$theta.b[2]
                                     ,sigeps1 = settings$sigeps[1]
                                     ,sigeps2 = settings$sigeps[2]
                                     ,h1 = settings$h[1]
                                     ,h2 = settings$h[2]
                                     ,ref = 2) %>%
                                mutate(delta = -delta)) # flip to group 2 - group 1
                            

    load(paste0(bf,'dcomps-ref1-GAM-QQ-CF-setting-',k,'.RData'))
    
    bench_ref1 <- dcomps_ref1 %>%
                    group_by(type, tau) %>%
                    summarize(delta.adj = mean(delta.adj)) %>%
                    mutate(ref = 1)
  
    load(paste0(bf,'dcomps-ref2-GAM-QQ-CF-setting-',k,'.RData'))
    bench_ref2 <- dcomps_ref2 %>%
                    group_by(type, tau) %>%
                    summarize(delta.adj = mean(delta.adj)) %>%
                    mutate(ref = 2)
    
    bench <- bench_ref1 %>%
                    bind_rows(bench_ref2) %>%
                    mutate(setting_id = k
                           ,n1 = settings$n[1]
                           ,n2 = settings$n[2]
                           ,alpha1 = settings$alpha[1]
                           ,alpha2 = settings$alpha[2]
                           ,beta1 = settings$beta[1]
                           ,beta2 = settings$beta[2]
                           ,theta.a1 = settings$theta.a[1]
                           ,theta.a2 = settings$theta.a[2]
                           ,theta.b1 = settings$theta.b[1]
                           ,theta.b2 = settings$theta.b[2]
                           ,sigeps1 = settings$sigeps[1]
                           ,sigeps2 = settings$sigeps[2]
                           ,h1 = settings$h[1]
                           ,h2 = settings$h[2])
    bench1Mgam <- bench1Mgam %>%
                   bind_rows(bench)
    
  }
```



# Merge in naive estimates to each row and compute differences
```{r}
stack.sum <- diffs %>%
            mutate(estimate = if_else(est == 'adjusted','Adjusted','Naive')
                  , nn = if_else(estimate == 'Adjusted', paste0(cal,'+',den),' naive')) %>%
              group_by(tau, nn, estimate, est, cal ,den
                       , n1, n2, alpha1, alpha2, h1, h2
                       , theta.a1, theta.a2, theta.b1, theta.b2
                       , sigeps1, sigeps2, refgp, setting_id) %>%
              summarize(delta.mean = mean(delta)
                        ,delta.lower = quantile(delta,0.025)
                        ,delta.upper = quantile(delta,0.975)
                        ,delta.se = sd(delta)
                        ,n=n())          
```

# Make Figure 2
```{r}
shortstack <- stack.sum %>%
     filter(est %in% c("adjusted", "naive (np)")) %>%
     filter(tau == 0.2) %>%
     rename(b2 = theta.b2
             ,a2 = theta.a2) %>%
     mutate(alab = factor(a2,levels = c("-0.5","-0.25","0","0.25","0.5")
                             ,labels = c("a[2]: -0.5","a[2]: -0.25","a[2]: 0","a[2]: 0.25","a[2]: 0.5"))
             ,blab = paste0("b[2]: ",b2) 
             ,Setting = factor(setting_id, levels = c(1,5,16,20), labels = c("L1","L2","C1","C2"))
            ,Reference =refgp  )

shortbench1M <- bench1Mgam%>%
     filter(tau == 0.2) %>%
    filter(type == "GAM") %>%
     rename(b2 = theta.b2
             ,a2 = theta.a2
            ,delta = delta.adj) %>%
     mutate(estimate= ' Benchmark'
            #,nn = paste(' Benchmark',type)) %>%
            ,nn = ' benchmark') %>%
   mutate(alab = factor(a2,levels = c("-0.5","-0.25","0","0.25","0.5")
                             ,labels = c("a[2]: -0.5","a[2]: -0.25","a[2]: 0","a[2]: 0.25","a[2]: 0.5"))
          ,blab = paste0("b[2]: ",b2)
          ,Setting = factor(setting_id, levels = c(1,5,16,20), labels = c("L1","L2","C1","C2"))
          ,Reference =ref )
```


```{r}
ggplot() +
      geom_pointrange(data= shortstack, aes(x=nn, y=delta.mean, ymin=delta.lower, ymax=delta.upper, color=estimate), size = 0.2) +
      geom_hline(yintercept=0, lty=2) +  # add a dotted line at x=1 after flip
      geom_point(data = shortbench1M,aes(x=nn, y=delta,color=estimate)) + 
      coord_flip() +  # flip coordinates (puts labels on y axis) 
      scale_x_discrete() +
      xlab("Estimation Method") +
      ylab(expression(paste("Difference in (a)TPRs, ",Delta))) + 
      theme_bw() + 
      scale_color_manual(name='Estimation Method',values = c('Adjusted' = 'black', 'Naive' = 'maroon',  ' Benchmark' = 'deepskyblue')) +
      scale_linetype_manual(name='Estimation Method',values = c('Adjusted' = 'solid', 'Naive' = 'solid', ' Benchmark' = 'solid'))  +
      facet_grid(Setting ~ Reference, labeller = label_both) +
      theme(legend.position="bottom") 

ggsave(paste0("R1-dTPR-Forest_",simlab,"-8panel-GAMmean.eps"),height=6.5,width=6, dpi = 300)
```