---
title: "12 Adjusted TPR"
subtitle: "aTPR - PNAS manuscript (revision) - Supplemental RWD Plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libs, include= FALSE}
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(patchwork)
library(ggh4x)

folder = '/Volumes/home_hegarty/D12-aTPR/12.05.01/rwdout/'
simlab = 'rwd03-palliative-connect-replicate-original-R1-'
```

# Make Supplemental Figure - Gender
```{r supfig.gender}
# Read in bootstrapped estimates
load(paste0(folder,simlab,'gender.Rdata'))

# Merge in naive estimates to each row and compute differences
diffs.gender <- gender.boot.comp %>%
                    filter(GENDER_CODE != 'M') %>%
                    mutate(estimate= 'adjusted'
                           , method = paste0(calmethod,"+",densitymethod)) %>%
                    bind_rows(gender.boot.comp %>%
                                  filter(GENDER_CODE != 'M') %>%
                                  select(GENDER_CODE, idset, tau, TPR) %>%
                                  unique() %>%
                                  mutate(estimate = 'naive'
                                         , method = 'none')
                    ) %>%
                left_join(gender.boot.comp  %>%
                            filter(GENDER_CODE == 'M') %>%
                            select(idset, tau, TPR) %>%
                            unique() %>%
                            rename(TPR.ref = TPR)
                          ) %>%
                mutate(delta = if_else(estimate == 'naive', TPR-TPR.ref, aTPR-TPR.ref))

# Get mean and CIs for delta
diffs.gender.sum <- diffs.gender %>%
                      group_by(GENDER_CODE, tau, estimate, method, calmethod, densitymethod) %>%
                      summarize(n = n()
                                ,delta.boot.mean = mean(delta)
                                ,delta.boot.lower =quantile(delta,0.025)
                                ,delta.boot.upper = quantile(delta, 0.975)
                                )
diffs.gender.sum %>% pull(n) %>% unique()

# Make figure by tau
diffs.gender.sum %>%
  filter(tau %in% seq(0.2,0.6,0.1)) %>%
  ggplot(aes(x = tau, y = delta.boot.mean, ymin = delta.boot.lower, ymax = delta.boot.upper)) +
      geom_pointrange(size = 0.2) +
      geom_hline(yintercept=0, lty=2) +  # add a dotted line at x=1 after flip
      xlab(expression(paste("Decision Threshold, ",tau))) + 
      ylab(expression(paste("Difference in (a)TPRs, ",Delta))) + 
      facet_grid(GENDER_CODE ~ estimate*method)+
      theme_bw() + 
      scale_color_manual(name='Estimate Type',values = c('Adjusted' = 'black', 'Naive' = 'maroon', 'Benchmark' = 'deepskyblue')) +
      scale_linetype_manual(name='Estimate Type',values = c('Adjusted' = 'solid', 'Naive' = 'solid', 'Benchmark' = 'solid'))  +
      theme(legend.position="bottom")

# Save plot
ggsave(paste0("supfigs/dTPR-Forest_",simlab,"gender.png"),height=4,width=6, dpi = 300)
```

# Make Supplemental Figure - Race
```{r supfig.race}
# Read in bootstrapped estimates
load(paste0(folder,simlab,'race.Rdata'))

# Merge in naive estimates to each row and compute differences
diffs.race <- race.boot.comp %>%
                    filter(race_ethnicity != 'Non_hispanic_white') %>%
                    mutate(estimate= 'adjusted'
                           , method = paste0(calmethod,"+",densitymethod)) %>%
                    bind_rows(race.boot.comp %>%
                                  filter(race_ethnicity != 'Non_hispanic_white') %>%
                                  select(race_ethnicity, idset, tau, TPR) %>%
                                  unique() %>%
                                  mutate(estimate = 'naive'
                                         , method = 'none')
                    ) %>%
                left_join(race.boot.comp  %>%
                            filter(race_ethnicity == 'Non_hispanic_white') %>%
                            select(idset, tau, TPR) %>%
                            unique() %>%
                            rename(TPR.ref = TPR)
                          ) %>%
                mutate(delta = if_else(estimate == 'naive', TPR-TPR.ref, aTPR-TPR.ref))

# Get mean and CIs for delta
diffs.race.sum <- diffs.race %>%
                      group_by(race_ethnicity, tau, estimate, method, calmethod, densitymethod) %>%
                      summarize(n = n()
                                ,delta.boot.mean = mean(delta)
                                ,delta.boot.lower =quantile(delta,0.025)
                                ,delta.boot.upper = quantile(delta, 0.975)
                                )
diffs.race.sum %>% pull(n) %>% unique()

# Make figure by tau
diffs.race.sum %>%
  filter(tau %in% seq(0.2,0.6,0.1)) %>%
  ggplot(aes(x = tau, y = delta.boot.mean, ymin = delta.boot.lower, ymax = delta.boot.upper)) +
      geom_pointrange(size = 0.2) +
      geom_hline(yintercept=0, lty=2) +  # add a dotted line at x=1 after flip
      xlab(expression(paste("Decision Threshold, ",tau))) + 
      ylab(expression(paste("Difference in (a)TPRs, ",Delta))) + 
      facet_grid(race_ethnicity ~ estimate*method)+
      theme_bw() + 
      scale_color_manual(name='Estimate Type',values = c('Adjusted' = 'black', 'Naive' = 'maroon', 'Benchmark' = 'deepskyblue')) +
      scale_linetype_manual(name='Estimate Type',values = c('Adjusted' = 'solid', 'Naive' = 'solid', 'Benchmark' = 'solid'))  +
      theme(legend.position="bottom")

# Save plot
ggsave(paste0("supfigs/dTPR-Forest_",simlab,"race.png"),height=4,width=6, dpi = 300)
```


# Make Supplemental Figure - GenderXRace
```{r supfig.genderrace}
# Read in bootstrapped estimates
load(paste0(folder,simlab,'genderrace.Rdata'))

# Merge in naive estimates to each row and compute differences
diffs.genderrace <- genderrace.boot.comp %>%
                    filter(GENDERxRACE != 'M-Non_hispanic_white') %>%
                    mutate(estimate= 'adjusted'
                           , method = paste0(calmethod,"+",densitymethod)) %>%
                    bind_rows(genderrace.boot.comp %>%
                                  filter(GENDERxRACE != 'M-Non_hispanic_white') %>%
                                  select(GENDERxRACE, idset, tau, TPR) %>%
                                  unique() %>%
                                  mutate(estimate = 'naive'
                                         , method = 'none')
                    ) %>%
                left_join(genderrace.boot.comp  %>%
                            filter(GENDERxRACE == 'M-Non_hispanic_white') %>%
                            select(idset, tau, TPR) %>%
                            unique() %>%
                            rename(TPR.ref = TPR)
                          ) %>%
                mutate(delta = if_else(estimate == 'naive', TPR-TPR.ref, aTPR-TPR.ref))

# Get mean and CIs for delta
diffs.genderrace.sum <- diffs.genderrace %>%
                      group_by(GENDERxRACE, tau, estimate, method, calmethod, densitymethod) %>%
                      summarize(n = n()
                                ,delta.boot.mean = mean(delta)
                                ,delta.boot.lower =quantile(delta,0.025)
                                ,delta.boot.upper = quantile(delta, 0.975)
                                )
diffs.genderrace.sum %>% pull(n) %>% unique()

# Make figure by tau
diffs.genderrace.sum %>%
  filter(tau %in% seq(0.2,0.6,0.1)) %>%
  ggplot(aes(x = tau, y = delta.boot.mean, ymin = delta.boot.lower, ymax = delta.boot.upper)) +
      geom_pointrange(size = 0.2) +
      geom_hline(yintercept=0, lty=2) +  # add a dotted line at x=1 after flip
      xlab(expression(paste("Decision Threshold, ",tau))) + 
      ylab(expression(paste("Difference in (a)TPRs, ",Delta))) + 
      facet_grid(GENDERxRACE ~ estimate*method)+
      theme_bw() + 
      scale_color_manual(name='Estimate Type',values = c('Adjusted' = 'black', 'Naive' = 'maroon', 'Benchmark' = 'deepskyblue')) +
      scale_linetype_manual(name='Estimate Type',values = c('Adjusted' = 'solid', 'Naive' = 'solid', 'Benchmark' = 'solid'))  +
      theme(legend.position="bottom")

# Save plot
ggsave(paste0("supfigs/dTPR-Forest_",simlab,"genderrace.png"),height=8,width=6, dpi = 300)
```