---
title: "run-coverage-tables"
author: "Hegarty"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r L01-1}
rmarkdown::render("Coverage-GAM-1Mmean.Rmd"
                  ,params = list(k = 1
                                 ,h = "logit"
                                 ,a2 = 0
                                 ,b2 = 1)
                  ,output_file = "Coverage-GAM-1Mmean-L01-0-1.html")

rmarkdown::render("Coverage-GAM-1Mmean.Rmd"
                  ,params = list(k = 5
                                 ,h = "logit"
                                 ,a2 = 0.5
                                 ,b2 = 1)
                  ,output_file = "Coverage-GAM-1Mmean-L01-0.5-1.html")

rmarkdown::render("Coverage-GAM-1Mmean.Rmd"
                  ,params = list(k = 16
                                 ,h = "cloglog"
                                 ,a2 = 0
                                 ,b2 = 1)
                  ,output_file = "Coverage-GAM-1Mmean-C01-0-1.html")

rmarkdown::render("Coverage-GAM-1Mmean.Rmd"
                  ,params = list(k = 20
                                 ,h = "cloglog"
                                 ,a2 = 0.5
                                 ,b2 = 1)
                  ,output_file = "Coverage-GAM-1Mmean-C01-0.5-1.html")
```